export const PROJECTS = [
  {
    name: 'Track',
    nameEm: 'book',
    tags: ['React 19', 'TypeScript', 'Supabase', 'Tailwind'],
    url: 'https://trackbook-3qzb.vercel.app/',
    github: 'https://github.com/NelsonVargas04/TRACKBOOK',
    img: '/trackbook.png',
    imgFit: 'contain',
    accent: 'rgba(139,92,246,.35)',
    alt: false,
    // i18n keys resolved by useProjects hook
    categoryKey: 'category4',
    descKey: 'desc4',
  },
  {
    name: 'Shop',
    nameEm: '.ar',
    tags: ['React', 'Node.js', 'PostgreSQL', 'Sequelize'],
    url: 'https://shop-ro6blzxvv-nelsons-projects-c499b28f.vercel.app/',
    github: 'https://github.com/NelsonVargas04/shop.ar',
    img: '/shop.ar.png',
    accent: 'rgba(212,160,23,.3)',
    alt: true,
    categoryKey: 'category1',
    descKey: 'desc1',
  },
  {
    name: 'Split',
    nameEm: 'App',
    tags: ['React', 'TypeScript', 'Vite'],
    url: 'https://page-splitter.vercel.app/',
    github: 'https://github.com/NelsonVargas04/page-splitter',
    img: '/splitapp.png',
    accent: 'rgba(100,120,200,.35)',
    alt: false,
    categoryKey: 'category2',
    descKey: 'desc2',
  },
  {
    name: 'Pass',
    nameEm: 'Key',
    tags: ['JavaScript', 'CSS', 'HTML'],
    url: 'https://password-generator-3kjsq6wg3-nelsons-projects-c499b28f.vercel.app',
    github: 'https://github.com/NelsonVargas04/Password-generator',
    img: '/PassKey.png',
    accent: 'rgba(60,140,100,.35)',
    alt: true,
    categoryKey: 'category3',
    descKey: 'desc3',
  },
];
